#
# DigitalOcean App Platform Specification for Astro Engine
# Production-ready configuration
#
# Deploy with: doctl apps create --spec .do/app.yaml
# Update with: doctl apps update <app-id> --spec .do/app.yaml
#
# NOTE: Secrets are configured via DigitalOcean Console/CLI, not in this file
#

name: astro-engine
region: blr  # Bangalore, India

# Main API Service
services:
  - name: api
    # GitHub integration for auto-deploy
    github:
      repo: Astro-Engine/Astro_Engine_ORGNL
      branch: main
      deploy_on_push: true

    # Build from Dockerfile
    dockerfile_path: Dockerfile

    # Application configuration
    http_port: 5000

    # Instance sizing - Basic XXS (512MB RAM, shared CPU, $5/month)
    instance_size_slug: basic-xxs
    instance_count: 1

    # Health check configuration
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # Environment variables (non-secrets only)
    envs:
      # Flask configuration
      - key: FLASK_ENV
        value: "production"

      - key: FLASK_DEBUG
        value: "false"

      - key: HOST
        value: "0.0.0.0"

      - key: PORT
        value: "5000"

      - key: WORKERS
        value: "4"

      - key: TIMEOUT
        value: "120"

      - key: ENVIRONMENT
        value: "production"

      # Application paths
      - key: PYTHONPATH
        value: "/app"

      - key: EPHEMERIS_PATH
        value: "/app/astro_engine/ephe"

      - key: EPHEMERIS_CACHE_SIZE
        value: "1000"

      # Database Configuration (non-secret parts)
      - key: DB_NAME
        value: "postgres"

      - key: DB_HOST
        value: "aws-0-ap-southeast-1.pooler.supabase.com"

      - key: DB_PORT
        value: "5432"

      # Cache TTLs
      - key: CACHE_TTL_NATAL
        value: "86400"

      - key: CACHE_TTL_TRANSIT
        value: "3600"

      # OpenAI Configuration (non-secret)
      - key: OPENAI_ASSISTANT_ID
        value: "asst_TX9m2nAuLnMsoBMHfRAKPpsF"

      - key: OPENAI_MODEL
        value: "gpt-4o-mini"

      # OTP Configuration (non-secret)
      - key: CLIENT_ID_OTP
        value: "M05P9FTUCRKI182E3E9KIQ7DZM80VLH4"

      - key: APP_ID_OTP
        value: "FQ2OHRM7YGB1GE6K7U3L"

      # JWT Configuration (non-secret)
      - key: JWT_ALGORITHM
        value: "HS256"

      - key: JWT_ISSUER
        value: "ratan-astro-platform"

      - key: JWT_EXPIRATION_HOURS
        value: "24"

      # WebSocket Configuration
      - key: WEBSOCKET_AUTH_ENABLED
        value: "true"

      - key: WEBSOCKET_JWT_REQUIRED
        value: "true"

      - key: WEBSOCKET_AUTH_ROLLOUT_PERCENTAGE
        value: "100"

      # Security Settings (non-secret)
      - key: API_KEY_REQUIRED
        value: "false"

      # CORS configuration
      - key: CORS_ORIGINS
        value: "*"

      # Rate Limiting (internal services - high limits)
      - key: RATE_LIMIT_CORP_BACKEND
        value: "1000000 per hour"

      - key: RATE_LIMIT_ASTRO_RATAN
        value: "1000000 per hour"

      - key: RATE_LIMIT_REPORT_ENGINE
        value: "1000000 per hour"

      - key: RATE_LIMIT_TESTING
        value: "1000000 per hour"

      - key: RATE_LIMIT_DEFAULT
        value: "1000000 per hour"

      # Logging configuration
      - key: LOG_LEVEL
        value: "INFO"

      - key: LOG_FILE
        value: "/app/logs/astro_engine.log"

      - key: LOG_MAX_BYTES
        value: "104857600"

      - key: LOG_BACKUP_COUNT
        value: "5"

      # Monitoring
      - key: METRICS_ENABLED
        value: "true"

      - key: HEALTH_CHECK_ENABLED
        value: "true"

      # Cache configuration
      - key: CACHE_ENABLED
        value: "true"

      - key: CACHE_DEFAULT_TIMEOUT
        value: "3600"

      # API Key Authentication
      - key: AUTH_REQUIRED
        value: "true"

      - key: AUTH_EXEMPT_ROUTES
        value: "/health,/metrics,/auth/health,/auth/stats,/auth/keys/info"

      # Request Size Limits
      - key: MAX_REQUEST_SIZE_MB
        value: "1"

# Ingress configuration
ingress:
  rules:
    - component:
        name: api
      match:
        path:
          prefix: /
